package vista;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import conexion.Conexion;
import controlador.Ctrl_Producto;
import controlador.Ctrl_RegistrarVenta;
import controlador.VentaPDF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CabeceraVenta;
import modelo.DetalleVenta;
import modelo.Producto;
import java.sql.PreparedStatement;
import java.util.Iterator;

/**
 *
 * @author Fernando Davila
 */
public class InterFacturacion extends javax.swing.JInternalFrame {

    //modelo de datos
    private DefaultTableModel modeloDatosProductos;
    //lista para el detalle de venta de los productos
    ArrayList<DetalleVenta> listaProductos = new ArrayList<>();
    private DetalleVenta producto;

    private int idProducto = 0;
    private String nombre = "";
    private int cantidadProductoBBDD = 0;
    private double precioUnitario = 0.0;
    private int porcentajeIva = 0;

    private int cantidad = 0;//de productos a comprar
    private double subtotal = 0.0;
    private double descuento = 0.0;
    private double iva = 0.0;
    private double totalpagar = 0.0;

    //variavles para calcular el totaL
    private double subtotalGeneral = 0.0;
    private double descuentoGeneral = 0.0;
    private double ivaGeneral = 0.0;
    private double totalPagarGeneral = 0.0;

    //auxiliar para el id de venta
    private int auxIdDetalle = 1;

    //id del cliente seleccionado
    private int idCliente = 0;

    /**
     * Creates new form InterFacturacion
     */
    public InterFacturacion() {
        initComponents();
        this.setSize(new Dimension(800, 600));
        this.setTitle("Facturación");

        //cargar clientes en combobox
        this.CargarComboClientes();
        //cargar productos en combobox
        this.CargarComboProductos();
        //inicializamos la tabla
        this.inicializarTablaProductos();

        txt_efectivo.setEnabled(false);
        jButton_calcular_cambio.setEnabled(false);

        txt_subtotal.setText("0.0");
        txt_iva.setText("0.0");
        txt_descuento.setText("0.0");
        txt_total_pagar.setText("0.0");

        ///insertar imagen en nuestro jLabel
        ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(800, 600, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    //metodo para inicializar la tavla de los productos
    private void inicializarTablaProductos() {

        modeloDatosProductos = new DefaultTableModel();
        //añadiremos las columnas
        modeloDatosProductos.addColumn("N");
        modeloDatosProductos.addColumn("Nombre");
        modeloDatosProductos.addColumn("Cantidad");
        modeloDatosProductos.addColumn("P. Unitario");
        modeloDatosProductos.addColumn("SubTotal");
        modeloDatosProductos.addColumn("Descuento");
        modeloDatosProductos.addColumn("IGV");
        modeloDatosProductos.addColumn("Total");
        modeloDatosProductos.addColumn("Acción");

        //agregar los datos del modelo a la tabla
        this.jTable_productos.setModel(modeloDatosProductos);
    }

    //metodo para presentar el array en la tabla detalles de venta
    private void listaTablaProductos() {

        this.modeloDatosProductos.setRowCount(listaProductos.size());

        for (int i = 0; i < listaProductos.size(); i++) {
            this.modeloDatosProductos.setValueAt(i + 1, i, 0);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getNombre(), i, 1);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getCantidad(), i, 2);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getPrecioUnitario(), i, 3);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getSubTotal(), i, 4);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getDescuento(), i, 5);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getIva(), i, 6);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getTotalPagar(), i, 7);
            this.modeloDatosProductos.setValueAt("Eliminar", i, 8);

        }
        //añadimos a la tabla
        jTable_productos.setModel(modeloDatosProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jComboBox_producto = new javax.swing.JComboBox<>();
        txt_cantidad = new javax.swing.JTextField();
        txt_cliente_buscar = new javax.swing.JTextField();
        jButton_añadir_producto = new javax.swing.JButton();
        jButton_buscar_cliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total_pagar = new javax.swing.JTextField();
        txt_efectivo = new javax.swing.JTextField();
        txt_cambio = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        jButton_calcular_cambio = new javax.swing.JButton();
        jButton_Registrar_venta = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Facturación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jComboBox_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        jComboBox_producto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:", "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 60, -1));

        txt_cliente_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_cliente_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, -1));

        jButton_añadir_producto.setBackground(new java.awt.Color(51, 51, 255));
        jButton_añadir_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_añadir_producto.setForeground(new java.awt.Color(204, 255, 255));
        jButton_añadir_producto.setText("Añadir producto");
        jButton_añadir_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadir_productoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_añadir_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 130, -1));

        jButton_buscar_cliente.setBackground(new java.awt.Color(0, 102, 51));
        jButton_buscar_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_buscar_cliente.setForeground(new java.awt.Color(204, 255, 255));
        jButton_buscar_cliente.setText("Buscar");
        jButton_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 760, 210));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("IGV:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Descuento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Efectivo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Subtotal:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cambio:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total a pagar:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_descuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descuento.setEnabled(false);
        jPanel2.add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        txt_iva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_iva.setEnabled(false);
        jPanel2.add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        txt_total_pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_pagar.setEnabled(false);
        jPanel2.add(txt_total_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        txt_efectivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, -1));

        txt_cambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cambio.setEnabled(false);
        jPanel2.add(txt_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, -1));

        txt_subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_subtotal.setEnabled(false);
        jPanel2.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        jButton_calcular_cambio.setBackground(new java.awt.Color(51, 102, 255));
        jButton_calcular_cambio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_calcular_cambio.setForeground(new java.awt.Color(153, 255, 255));
        jButton_calcular_cambio.setText("Calcular cambio");
        jButton_calcular_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcular_cambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_calcular_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 380, 210));

        jButton_Registrar_venta.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Registrar_venta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Registrar_venta.setForeground(new java.awt.Color(255, 255, 204));
        jButton_Registrar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jButton_Registrar_venta.setText("Registrar venta");
        jButton_Registrar_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Registrar_venta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Registrar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registrar_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_clienteActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void jButton_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_clienteActionPerformed

        String clienteBuscar = txt_cliente_buscar.getText().trim();
        Connection cn = Conexion.conectar();

        String sql = "SELECT nombre, apellido FROM tb_cliente WHERE cedula='" + clienteBuscar + "'";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {

                jComboBox_cliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido"));

            } else {

                jComboBox_cliente.setSelectedItem("Seleccione cliente:");
                JOptionPane.showMessageDialog(null, "DNI de cliente incorrecta o no encontrada");

            }
            txt_cliente_buscar.setText("");
            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al buscar cliente, " + e);
        }


    }//GEN-LAST:event_jButton_buscar_clienteActionPerformed

    private void jButton_añadir_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadir_productoActionPerformed

        String combo = this.jComboBox_producto.getSelectedItem().toString();
        //validar que se selecciono producto
        if (combo.equalsIgnoreCase("Seleccione producto:")) {

            JOptionPane.showMessageDialog(null, "Seleccione un producto");

        } else {

            //validamos que haya ingresado una cantida
            if (!txt_cantidad.getText().isEmpty()) {

                //validamos que el usuario no ingrese caracteres no numericos en cantidad
                boolean validacion = validar(txt_cantidad.getText());

                //validamos la respuesta de validar
                if (validacion) {

                    //validamos que cantidad sea mayor a 0
                    if (Integer.parseInt(txt_cantidad.getText()) > 0) {

                        cantidad = Integer.parseInt(txt_cantidad.getText());
                        //metodo para obtener los datos del producto
                        this.DatosDelProducto();

                        //validamos la cantidad de productos no sea mayor al stock
                        if (cantidad <= cantidadProductoBBDD) {

                            subtotal = precioUnitario * cantidad;
                            totalpagar = subtotal + iva + descuento;

                            //redondeamos decimales
                            subtotal = (double) Math.round(subtotal * 100) / 100;
                            iva = (double) Math.round(iva * 100) / 100;
                            descuento = (double) Math.round(descuento * 100) / 100;
                            totalpagar = (double) Math.round(totalpagar * 100) / 100;

                            //creamos un nuevo producto
                            producto = new DetalleVenta(auxIdDetalle,
                                    1,
                                    idProducto,
                                    nombre,
                                    Integer.parseInt(txt_cantidad.getText()),
                                    precioUnitario,
                                    subtotal,
                                    descuento,
                                    iva,
                                    totalpagar,
                                    1//estado

                            );

                            //añadimos el producto a la lista
                            listaProductos.add(producto);

                            JOptionPane.showMessageDialog(null, "Producto agregado");
                            auxIdDetalle++;
                            txt_cantidad.setText("");
                            //volvemos a cargar el combo de productos
                            this.CargarComboProductos();
                            //metodo para calcular
                            this.CalcularTotalPagar();
                            //habilitamos los botones para guardar
                            txt_efectivo.setEnabled(true);
                            jButton_calcular_cambio.setEnabled(true);

                        } else {

                            JOptionPane.showMessageDialog(null, "La cantidad seleccionada supera el stock");

                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "La cantidad no puede ser 0 o negativo");
                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos en cantidad");

                }

            } else {

                JOptionPane.showMessageDialog(null, "Ingrese una cantidad");
            }

        }
        //cargamos el metodo de productos agregados

        this.listaTablaProductos();

    }//GEN-LAST:event_jButton_añadir_productoActionPerformed

    private void jButton_calcular_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcular_cambioActionPerformed

        if (!txt_efectivo.getText().isEmpty()) {

            boolean validacion = validarDouble(txt_efectivo.getText());
            //validamos que solo ingrese caracteres numericos
            if (validacion == true) {

                double dinero = Double.parseDouble(txt_efectivo.getText().trim());
                double totalDinero = Double.parseDouble(txt_total_pagar.getText().trim());
                //validamos que el monto sea positivo
                if (dinero < totalDinero) {

                    JOptionPane.showMessageDialog(null, "Dinero ingresado es insuficiente");

                } else {

                    double cambio = (dinero - totalDinero);
                    double camb = (double) Math.round(cambio * 100) / 100;
                    String cam = String.valueOf(camb);
                    txt_cambio.setText(cam);
                }

            } else {

                JOptionPane.showMessageDialog(null, "Ingrese el monto en caracteres solo numericos");
            }

        } else {

            JOptionPane.showMessageDialog(null, "Ingrese un monto de efectivo para calcular el cambio");

        }

    }//GEN-LAST:event_jButton_calcular_cambioActionPerformed

    int idArrayList = 0;
    private void jTable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productosMouseClicked

        int filaPoint = jTable_productos.rowAtPoint(evt.getPoint());
        int columnaPoint = 0;
        if (filaPoint > -1) {

            idArrayList = (int) modeloDatosProductos.getValueAt(filaPoint, columnaPoint);

        }
        int opcion = JOptionPane.showConfirmDialog(null, "¿Eliminar producto de la lista?");
        //opciones de confirmacion si = 0, no = 1, cancel=2, close=-1
        switch (opcion) {
            case 0:

                listaProductos.remove(idArrayList - 1);
                this.CalcularTotalPagar();
                this.listaTablaProductos();
                break;
            case 1:
                break;
            default:
                break;
        }


    }//GEN-LAST:event_jTable_productosMouseClicked

    private void jButton_Registrar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registrar_ventaActionPerformed

        CabeceraVenta cabeceraVenta = new CabeceraVenta();
        DetalleVenta detalleVenta = new DetalleVenta();
        Ctrl_RegistrarVenta controlVenta = new Ctrl_RegistrarVenta();

        String fechaActual = "";
        Date date = new Date();
        fechaActual = new SimpleDateFormat("yyyy/MM/dd").format(date);

        if (!jComboBox_cliente.getSelectedItem().equals("Seleccione cliente:")) {

            if (listaProductos.size() > 0) {

                //metodo para obtener el id del cliente
                this.ObtenerIdCliente();
                //registramos cabecera
                cabeceraVenta.setIdCabeceraVenta(0);
                cabeceraVenta.setIdCliente(idCliente);
                cabeceraVenta.setValorPagar(Double.parseDouble(txt_total_pagar.getText()));
                cabeceraVenta.setFechaVenta(fechaActual);
                cabeceraVenta.setEstado(1);

                if (controlVenta.guardar(cabeceraVenta)) {

                    JOptionPane.showMessageDialog(null, "Venta Registrada Correctamente");

                    //geramos la factura
                    VentaPDF pdf = new VentaPDF();
                    pdf.DatosCliente(idCliente);
                    pdf.generarFacturaPDF();

                    // Guardamos los detalles de la venta
                    Iterator<DetalleVenta> iterator = listaProductos.iterator();
                    while (iterator.hasNext()) {
                        DetalleVenta elemento = iterator.next();

                        detalleVenta.setIdDetalleVenta(0);
                        detalleVenta.setIdCabeceraVenta(0);
                        detalleVenta.setIdProducto(elemento.getIdProducto());
                        detalleVenta.setCantidad(elemento.getCantidad());
                        detalleVenta.setPrecioUnitario(elemento.getPrecioUnitario());
                        detalleVenta.setSubTotal(elemento.getSubTotal());
                        detalleVenta.setDescuento(elemento.getDescuento());
                        detalleVenta.setIva(elemento.getIva());
                        detalleVenta.setTotalPagar(elemento.getTotalPagar());
                        detalleVenta.setEstado(1);

                        if (controlVenta.guardarDetalle(detalleVenta)) {
                            txt_subtotal.setText("0.0");
                            txt_iva.setText("0.0");
                            txt_descuento.setText("0.0");
                            txt_total_pagar.setText("0.0");
                            txt_efectivo.setText("0.0");
                            txt_cambio.setText("0.0");
                            auxIdDetalle = 1;

                            this.CargarComboClientes();
                            // Método para actualizar stock
                            this.RestarStockProductos(elemento.getIdProducto(), elemento.getCantidad());

                            // Eliminar el elemento actual después de procesarlo
                            iterator.remove();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar el detalle de venta");
                        }
                    }

                    // Fuera del bucle, ahora puedes limpiar la lista
                    listaProductos.clear();
                    listaTablaProductos();

                } else {

                    JOptionPane.showMessageDialog(null, "Error al guardar cabecera de venta");
                }

            } else {

                JOptionPane.showMessageDialog(null, "Seleccione uno o varios productos");

            }

        } else {

            JOptionPane.showMessageDialog(null, "Seleccione un cliente");

        }


    }//GEN-LAST:event_jButton_Registrar_ventaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Registrar_venta;
    private javax.swing.JButton jButton_añadir_producto;
    private javax.swing.JButton jButton_buscar_cliente;
    private javax.swing.JButton jButton_calcular_cambio;
    private javax.swing.JComboBox<String> jComboBox_cliente;
    private javax.swing.JComboBox<String> jComboBox_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cliente_buscar;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_efectivo;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_subtotal;
    public static javax.swing.JTextField txt_total_pagar;
    // End of variables declaration//GEN-END:variables

    //metodo para cargar clientes
    private void CargarComboClientes() {

        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM tb_cliente";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_cliente.removeAllItems();
            jComboBox_cliente.addItem("Seleccione cliente:");

            while (rs.next()) {

                jComboBox_cliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));

            }
            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al cargar los clientes ," + e);
        }

    }

    //metodo para cargar productoz
    private void CargarComboProductos() {

        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM tb_producto";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_producto.removeAllItems();
            jComboBox_producto.addItem("Seleccione producto:");

            while (rs.next()) {

                jComboBox_producto.addItem(rs.getString("nombre"));

            }
            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al cargar los productos ," + e);
        }

    }

    //creamos el metodo para validar los caracteres
    private boolean validar(String valor) {

        try {
            int num = Integer.parseInt(valor);
            return true;

        } catch (NumberFormatException e) {

            return false;
        }

    }

    //creamos el metodo para validar los caracteres pero para double
    private boolean validarDouble(String valor) {

        try {
            double num = Double.parseDouble(valor);
            return true;

        } catch (NumberFormatException e) {

            return false;
        }

    }

    //metodo para mostrar los productos seleccionado
    private void DatosDelProducto() {

        try {

            String sql = "SELECT * FROM tb_producto WHERE nombre = '" + this.jComboBox_producto.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                idProducto = rs.getInt("idProducto");
                nombre = rs.getString("nombre");
                cantidadProductoBBDD = rs.getInt("cantidad");
                precioUnitario = rs.getDouble("precio");
                porcentajeIva = rs.getInt("porcentajeIva");

                this.CalcularIva(precioUnitario, porcentajeIva);

            }

        } catch (SQLException e) {

            System.out.println("Error al obtener datos del producto," + e);

        }

    }

    private double CalcularIva(double precio, int porcentaje) {

        int p_iva = porcentaje;
        switch (p_iva) {
            case 0:
                iva = 0.0;
                break;
            case 18:
                iva = (precio * cantidad) * 0.18;
                break;
            case 19:
                iva = (precio * cantidad) * 0.19;
                break;
            case 20:
                iva = (precio * cantidad) * 0.20;
                break;
            default:
                break;
        }

        return iva;

    }

    //metodo para calcular el total a pagar
    private void CalcularTotalPagar() {

        subtotalGeneral = 0;
        descuentoGeneral = 0;
        ivaGeneral = 0;
        totalPagarGeneral = 0;

        for (DetalleVenta elemento : listaProductos) {

            subtotalGeneral += elemento.getSubTotal();
            descuentoGeneral += elemento.getDescuento();
            ivaGeneral += elemento.getIva();
            totalPagarGeneral += elemento.getTotalPagar();

        }

        //redondeamos decimales
        subtotalGeneral = (double) Math.round(subtotalGeneral * 100) / 100;
        descuentoGeneral = (double) Math.round(descuentoGeneral * 100) / 100;
        ivaGeneral = (double) Math.round(ivaGeneral * 100) / 100;
        totalPagarGeneral = (double) Math.round(totalPagarGeneral * 100) / 100;

        //mostramos en la vista
        txt_subtotal.setText(String.valueOf(subtotalGeneral));
        txt_iva.setText(String.valueOf(ivaGeneral));
        txt_descuento.setText(String.valueOf(descuentoGeneral));
        txt_total_pagar.setText(String.valueOf(totalPagarGeneral));

    }
    //metodo para obtener el id del cliente

    private void ObtenerIdCliente() {

        try {

            String sql = "SELECT * FROM tb_cliente WHERE concat(nombre, ' ', apellido) = '" + this.jComboBox_cliente.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                idCliente = rs.getInt("idCliente");

            }

        } catch (SQLException e) {

            System.out.println("Error al obtener el id del cliente");
        }

    }

    //metodo para restar stock
    private void RestarStockProductos(int idProducto, int cantidad) {

        int cantidadProductoBaseDatos = 0;
        try {

            Connection cn = Conexion.conectar();
            String sql = "SELECT idProducto, cantidad FROM tb_producto WHERE idProducto = '" + idProducto + "'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                cantidadProductoBaseDatos = rs.getInt("cantidad");

            }
            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al obtener id de stock" + e);
        }

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement("UPDATE tb_producto set cantidad=? WHERE idProducto='" + idProducto + "'");
            int cantidadNueva = cantidadProductoBaseDatos - cantidad;
            consulta.setInt(1, cantidadNueva);
            if (consulta.executeUpdate() > 0) {

                System.out.println("Actualizacoon de stock correcta");

            }

            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al actualizar stock" + e);

        }

    }

}
